spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: fastdb
    password: fast@dev@)@)
    url: jdbc:mysql://192.168.22.213:23622/test_1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔 com.example.*.entity
  typeAliasesPackage: com.example.flowable_web.entity
  global-config:
    #数据库相关配置
    db-config:
    #主键类型 AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
    cache-enabled: false
    call-setters-on-nulls: true

#log配置
logging:
  file:
    path: D:\workspace\demo\flowable\log
    name: esg-bank-inner
  level:
    org.flowable.engine.impl.persistence.entity.*: debug
    org.flowable.task.service.impl.persistence.entity.*: debug
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 10KB

